name: Slack Notify on Star
on: watch
jobs:
  star-notify:
    name: Notify Slack on star
    runs-on: ubuntu-latest
    steps:
    - name: Get current star count
      run: |
        echo ::set-env name=STARS::$(curl --silent 'https://api.github.com/repos/leecalcote/containers-101/' -H 'Accept: application/vnd.github.preview' | jq '.watchers_count')
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CSK7N9TGX\",\"text\":\"Someone just starred Containers 101 Workshop! (https://github.com/leecalcote/containers-101/stargazers) Total ⭐️: ${{env.STARS}}\"}'